### ISSUE TITLE
Implementeer de sprinkhaan

### ISSUE THREAD

**Issue by mxike** [mxike/itvb23ows-starter-code-mike#1]
Voeg functionaliteit toe om de sprinkhaan te bewegen volgens de opgegeven regels.

## Todo
- [x] Implementeer de beweging van de sprinkhaan zodat hij in een rechte lijn een sprong maakt, naar een veld meteen achter een andere steen in de richting van de sprong.
- [x] Controleer of de sprong naar een legaal veld gaat volgens de regels (niet naar bezet veld springen, niet over lege velden springen).
- [x] Controleer: Zorg ervoor dat de sprinkhaan minstens één steen overslaat tijdens de sprong.
