### ISSUE TITLE
Implementeer de spin

### ISSUE THREAD

**Issue by mxike** [mxike/itvb23ows-starter-code-mike#3]
Voeg functionaliteit toe om de spin te bewegen volgens de opgegeven regels.

## Todo:
- [x] Implementeer de beweging van de spin door zich precies drie keer te verschuiven.
- [x] Controleer of de spin zich niet verplaats naar het veld waar hij al staat.
- [x] Controleer: De spin mag alleen verplaats worden over en naar lege velden.
- [x] Controleer: Een spin mag tijdens zijn verplaatsing geen stap maken naar een veld waar hij tijdens de verplaatsing al is geweest.
