### ISSUE TITLE
Fouten in dropdownopties voor plaatsen en verplaatsen van stenen

### ISSUE THREAD

**Issue by mxike** [mxike/itvb23ows-starter-code-mike#7]
**Beschrijving:** De dropdown-opties tonen stenen die de speler niet meer heeft en velden waar plaatsen/verplaatsen niet mogelijk is.

## Todo oplossen bugs:
- [ ] De dropdown geeft aan welke stenen een speler kan plaatsen, maar bevat ook stenen die de speler niet meer heeft.
- [ ] De dropdown geeft aan waar een speler de stenen kan plaatsen, waar dat niet mogelijk moet zijn.
- [ ] De dropdown geeft de positie van een speler aan waar hij een steen heen wil verplaatsen, maar deze bevatten ook velden waar stenen van de tegenstander zich bevinden.
